# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'ImagemathStudent' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for ImagemathStudent
	pod 'Firebase/Analytics'
	pod 'Firebase/Messaging'

  target 'ImagemathStudentTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'ImagemathStudentUITests' do
    # Pods for testing
  end

end
